### ISSUE TITLE
Need page breaks on longer posts w/ "read more"

### ISSUE THREAD

**Issue by knowtheory** [knowtheory/projectopenvault#18]

**Comment by knowtheory** [comment]
@mfr6yf @davidherzog: Hey guys, just wanted to let you know, that anyone can insert a page break either using the buttons in the editor, or writing "[[MORE]]" directly into their post wherever they want the page break to occur.

Matt, could you share that with the others please? :)

**Comment by mfr6yf** [comment]
I'll go ahead and send it along.

I just took a look at the site and the numbers for the ad buys are way off.
Some candidates who have run ads have no money next to their names while
others who haven't run any ads do. Is that just a glitch or did something
else get messed up?

Matt

On Mon, Aug 27, 2012 at 8:36 AM, Ted Han notifications@github.com wrote:

> @mfr6yf https://github.com/mfr6yf @DavidHerzoghttps://github.com/DavidHerzog:
> Hey guys, just wanted to let you know, that anyone can insert a page break
> either using the buttons in the editor, or writing "[[MORE]]" directly into
> their post wherever they want the page break to occur.
> 
> Matt, could you share that with the others please? :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/knowtheory/projectopenvault/issues/18#issuecomment-8055925.

## 

Matthew Patane
(314) 239-1263
patane.mf@gmail.com
Reporter, Missouri Digital News
University of Missouri

**Comment by knowtheory** [comment]
Nope.  David asked that we display only ad numbers that have run so far.  See #7

**Comment by knowtheory** [comment]
By the by, if you think it's worth it we can write up why we changed the numbers to display ads that have been fulfilled (especially with folks canceling their contracts for Todd Akin).

**Comment by mfr6yf** [comment]
I'm okay with just having the amount of ads that have run so far. I'm going
to go ahead and continue to add in future ad buys as they come in so I
don't lost track of them, unless it would be easier for me to do otherwise.

Even so, the numbers are still wrong. Brunner has $0 while Justin Harter
and Cissee Spragins (among others) have amounts next to them even though
neither of them has run any ads. I'm not sure where those numbers came
from, since their names shouldn't even be in the ad buy database, just the
candidate one.

On Mon, Aug 27, 2012 at 9:28 AM, Ted Han notifications@github.com wrote:

> By the by, if you think it's worth it we can write up why we changed the
> numbers to display ads that have been fulfilled (especially with folks
> canceling their contracts for Todd Akin).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/knowtheory/projectopenvault/issues/18#issuecomment-8057313.

## 

Matthew Patane
(314) 239-1263
patane.mf@gmail.com
Reporter, Missouri Digital News
University of Missouri

**Comment by knowtheory** [comment]
Oh crap, thanks for catching that.  I'd eyeballed them and chalked up the changes i'd seen due to the date range, but you're right that i screwed up the change, but it's now fixed.  Take a look and let me know if that seems more sensible.
